image: node:12.18.1

stages:
  - install
  - build
  - test

install:
  stage: install
  script:
    - yarn install
  cache:
    paths:
      - yarn
  artifacts:
    paths:
      - node_modules


build:
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - dist/

test:
  stage: test
  script:
    - yarn test
