stages:
    - install
    - build
    - test

install:
    stage: install
    script:
        - yarn install

build:
    stage: build
    script:
        - yarn build

test:
    stage: test
    script:
        - yarn test